### ISSUE TITLE
Credential.refreshIfNeeded fails on iOS

### ISSUE THREAD

**Issue by Sushree-nayak-2022** [okta/okta-idx-swift#118]
### Describe the bug?

I am facing this bug and blocked because of below issue which is reported here
https://github.com/okta/okta-mobile-swift/issues/101
I see  [okta-mobile-swift](https://github.com/okta/okta-mobile-swift) is updated with the fix recently..

Can you please update this sdk  [okta-idx-swift](https://github.com/okta/okta-idx-swift) which internally uses okta-mobile-swift

### What is expected to happen?

Token refresh is not working using okta-idx-swift. the provided function refreshIfNeeded is not refreshing the token.

### What is the actual behavior?

Token should gets refreshed using refreshIfNeeded function from okta-idx-swift sdk. But refresh is failing

### Reproduction Steps?

login to the Sample app and on profile screen click on refresh which calls refresh() function, which is not working and tokens are not refreshing

### Additional Information?

I am facing this bug and blocked because of below issue which is reported here
https://github.com/okta/okta-mobile-swift/issues/101
I see  [okta-mobile-swift](https://github.com/okta/okta-mobile-swift) is updated with the fix recently..

Can you please update this sdk  [okta-idx-swift](https://github.com/okta/okta-idx-swift) which internally uses okta-mobile-swift

### SDK Version(s)

3.0.2

**Comment by mikenachbaur-okta** [comment]
@Sushree-nayak-2022 I have [released 3.0.3](https://github.com/okta/okta-idx-swift/releases/tag/3.0.3) which updates the upstream version dependency, as well as addresses a few minor bug fixes.
