### ISSUE TITLE
Tokens not getting saved after refreshing

### ISSUE THREAD

**Issue by Sushree-nayak-2022** [okta/okta-idx-swift#120]
### Describe the bug?

credential.refreshIfNeeded is not updating Credential.default after token gets refreshed successfully.

### What is expected to happen?

up on token refresh Credential.default should gets updated with the latest token value

### What is the actual behavior?

credential.refreshIfNeeded is not updating Credential.default after token gets refreshed successfully.

### Reproduction Steps?

Login
Get the latest tokens
Close the app open again we will get new pair of tokens but Credential.default will have the previous token only.
Close the app again and open. Now Credential.default has the same OLD token only which is invalid by this time and user is stuck now because those tokens are expired.

### SDK Version(s)

3.0.4

**Comment by mikenachbaur-okta** [comment]
Hi @Sushree-nayak-2022, I found another edge-case where this scenario can occur, and am working through the code path to find the root cause. My guess is that it's a race-condition, and I'll update this ticket when I find out more.

**Comment by mikenachbaur-okta** [comment]
Internal ref [OKTA-562398](https://oktainc.atlassian.net/browse/OKTA-562398)

**Comment by mikenachbaur-okta** [comment]
@Sushree-nayak-2022 I've just released [okta-idx-swift 3.0.5](https://github.com/okta/okta-idx-swift/releases/tag/3.0.5) which explicitly pulls in the new SDK version as a dependency.

**Comment by Sushree-nayak-2022** [comment]
Thank you very much @mikenachbaur-okta . It is working as expected now.
