### ISSUE TITLE
"The token has expired" message when the phone timezone is not the proper one.

### ISSUE THREAD

**Issue by andreeasinescusst** [okta/okta-idx-swift#131]
### Describe the bug?

When the user has set an incorrect local date, we receive when we try to log in the error "The token has expired", which is not great because we just logged in, and the message is not helpful at all.

### What is expected to happen?

We should receive an error that would lead the user to know that he needs to verify his timezone.

### What is the actual behavior?

When the user has set an incorrect local date, we receive when we try to log in the error "The token has expired".

### Reproduction Steps?

1. Change the timezone to Los Angeles
2. Try to login
3. You will receive the error "The token has expired".

### Additional Information?

In the SDK for the web from Okta, we receive "Unable to sign in. Please check that your device's clock is accurate and try again." when the user has his timezone set wrong.

### SDK Version(s)

3.0.8

**Comment by mikenachbaur-okta** [comment]
Hi @andreeasinescusst, is it just the timezone that is set differently? Or is the device's clock set to a custom time?

If you go into Settings > General > Date & Time, and ensure "Set Automatically" is enabled, does it work for you?

The Mobile SDK has a protocol called "[TimeCoordinator](https://okta.github.io/okta-mobile-swift/development/authfoundation/documentation/authfoundation/timecoordinator)" which can be used to ensure time calculations adjust for incorrect device times, though the current version of the SDK doesn't implement this as of yet.  In the future, we plan to add out-of-the-box support for this, but it's not in the currently shipping version of the SDK.

**Comment by andreeasinescusst** [comment]
Hi @mikenachbaur-okta, yes, it works when we enable "Set Automatically" from settings. How should we know what is the correct date and time to set in the TimeCoordinator?

**Comment by mikenachbaur-okta** [comment]
@andreeasinescusst I've created this PR https://github.com/okta/okta-mobile-swift/pull/118 which will address the auto-calculation of time drift for mobile clients. Once this is merged, it should be available within the next release. Please feel free to comment on that PR, if you have any additional feedback.

I'll make sure to tag you when the next release is pushed.

**Comment by mikenachbaur-okta** [comment]
@andreeasinescusst I just released [okta-mobile-swift 1.3.0](https://github.com/okta/okta-mobile-swift/releases/tag/1.3.0) which includes this fix, so I'll be closing this issue.

If anything else comes up, please don't hesitate to reach out here!
