### ISSUE TITLE
Polling stops in the event of temporary network loss

### ISSUE THREAD

**Issue by dancinnamon-okta** [okta/okta-idx-swift#145]
### Describe the bug?

During an email magic link flow, polling is supposed to be occuring in the IDX SDK- properly discovering when the user has consented to the login within their email app and/or browser. However instead, when network connection is lost, we instead cancel all polling- leaving applications to hang.

### What is expected to happen?

Upon loss of network, the Polling Handler is supposed to retry it's polling from the last successful poll response from Okta.

### What is the actual behavior?

In the IDXPollableCapability.startPolling method- if NSURLErrorNetworkConnectionLost is caught, we return a null back to the PollHandler.
https://github.com/okta/okta-idx-swift/blob/8174fe60564d2ca2a54b641623faaa8077877ead/Sources/OktaIdx/Capabilities/IDXPollableCapability.swift#L39C57-L39C88

In this event, nil is returned, and the PollHandler will invoke the stopPolling method.
https://github.com/okta/okta-idx-swift/blob/8174fe60564d2ca2a54b641623faaa8077877ead/Sources/OktaIdx/Internal/Utilities/PollingHandler.swift#L64

### Reproduction Steps?

Launch an email magic link flow using this IDX SDK, and then, while polling, sever and restart the network connection of the device. Then accept/consent to the magic link in Okta. Polling will stop, and upon return to the app, the user will still not be logged in.

### SDK Version(s)

3.1.0 - latest

**Comment by mikenachbaur-okta** [comment]
Thanks for filing this; as we discussed on Zoom, this does seem to be a legitimate case where polling may be interrupted, so I'll start looking into this right away.

**Comment by mikenachbaur-okta** [comment]
@dancinnamon-okta I have a fix in #146, which will be merged and released in the morning.
